SELECT ATTACHMENTS.ID AS attachment_id,
ATTACHMENTS.CREATE_DATE AS attachment_create_date,
ATTACHMENTS.CREATE_BY AS attachment_create_by,
USERS.FIRST_NAME AS create_by_first_name,
USERS.LAST_NAME AS create_by_last_name,
ATTACHMENTS.FILE_NAME AS attachment_file_name
FROM ATTACHMENTS
LEFT JOIN USERS ON ATTACHMENTS.CREATE_BY = USERS.ID
WHERE ATTACHMENTS.ISSUE_ID = 1;

INSERT INTO ATTACHMENTS (ISSUE_ID, CREATE_DATE, CREATE_BY, FILE_NAME)
VALUES
(1, CURRENT_DATE, 4, 'test.txt');

DELETE FROM ATTACHMENTS WHERE ATTACHMENTS.ID > 2;