select * from USERS;
create table users (
  user_name varchar(15) not null primary key,
  user_pass varchar(15) not null
);

create table user_roles (
  user_name varchar(15) not null,
  role_name varchar(15) not null,
  primary key (user_name, role_name)
);

create table users (
    id INTEGER not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
    first_name varchar(50) not null,
    last_name varchar(50) not null,
    email varchar(50) not null,
    password varchar(50) not null
);

create table properties (
	id INTEGER not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
	prop_type varchar(20) not null,
	prop_name  varchar(20) not null
);

create table projects (
	id INTEGER not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
	project_name varchar(20) not null,
	description  varchar(300) not null,
	manager INTEGER not null,
	CONSTRAINT fk_manager FOREIGN KEY (manager) REFERENCES users(id)
	
);