SELECT PROJECTS.ID AS project_id, 
PROJECTS.PROJECT_NAME AS project_name,
PROJECTS.DESCRIPTION AS project_description,
PROJECTS.MANAGER AS project_manager_id,
USERS.FIRST_NAME AS project_manager_first_name,
USERS.LAST_NAME AS project_manager_last_name
FROM PROJECTS
LEFT JOIN USERS ON PROJECTS.MANAGER = USERS.ID;

SELECT PROJECTS.ID AS project_id, 
PROJECTS.PROJECT_NAME AS project_name
FROM PROJECTS;

SELECT BUILDS.ID AS build_id,
BUILDS.BL_NAME AS build_name,
BUILDS.PROJECT_ID AS project_id
FROM BUILDS
WHERE BUILDS.PROJECT_ID = 1;