SELECT PRIORITIES.ID AS id,
PRIORITIES.PR_NAME AS name
FROM PRIORITIES;

SELECT STATUSES.ID AS status_id,
STATUSES.ST_NAME AS status_name
FROM STATUSES;

SELECT TYPES.ID AS id,
TYPES.TP_NAME AS name
FROM TYPES
WHERE TYPES.ID =1;

SELECT RESOLUTIONS.ID AS id,
RESOLUTIONS.RES_NAME AS name
FROM RESOLUTIONS;

SELECT ROLES.ID AS id,
ROLES.RL_NAME AS name
FROM ROLES;

INSERT INTO STATUSES (ST_NAME) VALUES ('TEST');
INSERT INTO RESOLUTIONS (RES_NAME) VALUES ();
INSERT INTO PRIORITIES (PR_NAME) VALUES ();
INSERT INTO TYPES (TP_NAME) VALUES ();
INSERT INTO ROLES (RL_NAME) VALUE ();

UPDATE STATUSES SET STATUSES.ST_NAME = 'NOT TEST' WHERE STATUSES.ID = 8;
UPDATE RESOLUTIONS SET RESOLUTIONS.RES_NAME = 'TEST' WHERE RESOLUTIONS.ID = 1;
UPDATE PRIORITIES SET PRIORITIES.PR_NAME = 'TEST' WHERE PRIORITIES.ID = 1;
UPDATE TYPES SET TYPES.TP_NAME = 'TEST' WHERE TYPES.ID = 1;
UPDATE ROLES SET ROLES.RL_NAME = 'TEST' WHERE ROLES.ID = 1;

DELETE FROM STATUSES WHERE STATUSES.ID = 9;
DELETE FROM RESOLUTIONS WHERE RESOLUTIONS.ID = 1;
DELETE FROM PRIORITIES WHERE PRIORITIES.ID = 1;
DELETE FROM TYPES WHERE TYPES.ID = 1;
DELETE FROM ROLES WHERE ROLES.ID = 1;